// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wucphkgntxkbiyblxuso.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind1Y3Boa2dudHhrYml5Ymx4dXNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NzQxNDYsImV4cCI6MjA2NjI1MDE0Nn0.XqDbFctWvjoBDfsEkX7bGQj-7jQTd6dRcWmmg9Kqbq0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);